---
logLevel: null
logFile: null

## More than one database can be defined, you can pass the database id to BioNetDBManager.
## If not passed the default database will always be the first one.
databases:
- id: "${BIONETDB.DB.DATABASE}"
  species: "${BIONETDB.DB.SPECIES}"     ## examples: hsapiens, mmusculus, ...
  host: "${BIONETDB.DB.HOST}"
  port: "${BIONETDB.DB.PORT}"
  user: "${BIONETDB.DB.USER}"
  password: "${BIONETDB.DB.PASSWORD}"
  options: null                         ## map containing specific database options
